Algoritmo "Atv12Exc5"

Var

 numero1:inteiro
 numero2:inteiro
 dif:real
 
Inicio

escreval ("informe o primeiro numero")
leia (numero1)
escreval ("informe o segundo numero")
leia (numero2)

se (numero1>=numero2)entao
dif:= numero1-numero2
escreval ("a diferenca eh: ", dif)
fimse
se (numero2>numero1)entao
dif: numero2-numero1)
escreval ("a diferenca eh: ", dif)
fimse

Fimalgoritmo