Algoritmo "Atv12Exc1"

Var

   valor:real

Inicio

   escreva ("informe o valor desejado ")
   leia (valor)
   escreva ("")
   se (valor<10) entao
      escreval ("o valor digitado eh menor que 10")
   fimse
   se (valor>10) entao
      escreval ("o valor digitado eh maior que 10")
   fimse
   se (valor=10) entao
      escreval ("o valor eh igual a 10")
   fimse
   
Fimalgoritmo