Algoritmo "Exercicio6"

Var



Inicio

            escreval ("Nome Completo: Lucas Andrusievicz")
            escreval ("Endereço: R. Maurício Nunes García")
            escreval ("Numero: 289")
            escreval ("Complemento: Casa cinza")
            escreval ("CEP: 80210-150")
            escreval ("Bairro: Jardim Botânico")
            escreval ("Estado: Paraná")
            escreval ("Pais: Brasil")
            


Fimalgoritmo