Algoritmo "Variavel8"

Var

valor1:real
valor2:real
valor3:real
valor4:real
resultado:real

Inicio

escreval ("Digite a primeira nota do aluno")
leia (valor1)
escreval ("Digite a segunda nota do aluno")
leia (valor2)
escreval ("Digite a terceira nota do aluno")
leia (valor3)
escreval ("Digite a quarta nota do aluno")
leia (valor4)
resultado:= (valor1+valor2+valor3+valor4)/4)
escreval ("A media anual do aluno eh:", resultado)

Fimalgoritmo