Algoritmo "Variavel3"

Var

Valor1:inteiro
Valor2:inteiro
Valor3:inteiro
Valor4:inteiro
Resultado:real

Inicio

escreval ("Digite o primeiro valor da soma")
leia (Valor1)
escreval ("Digite o segundo valor da soma")
leia (Valor2)
escreval ("Digite o terceiro valor da soma")
leia (Valor3)
escreval ("Digite o valor da subtracao")
Leia (Valor4)
Resultado:= (Valor1+Valor2+Valor3-Valor4)
escreval ("O valor da conta 45+67+12-45 eh:", Resultado)

Fimalgoritmo