Algoritmo "Atv7exc2"

Var

salario:real
valorfinal:real
valorfinal1:real
Inicio


escreval ("digite o valor do salario")
leia (salario)
limpatela
valorfinal:= salario*0.25
valorfinal1:= valorfinal+salario
escreval ("o funcionario com o salario de:", salario)
escreval ("obeteve um aumento de 25% que resultou em um aumento de:", valorfinal)
escreva ("totalizando em um salario de:", valorfinal1)

Fimalgoritmo