Algoritmo "Atv7exc5"

Var

valor1:real
tri1:real
tri2:real
valorfinal:real

Inicio

escreval ("Informe o valor desejado para o deposito na poupanca")
leia (valor1)
tri1:= valor1*0.02
tri2:= valor1*0.035
valorfinal:= tri1+tri2
limpatela
escreval ("Valor depositado inicialmente: ", valor1)
escreval ("Rendimento no primeiro trimestre: ", tri1)
escreval ("Rendimento no segundo trimestre: ", tri2)
escreval ("O rendimento total eh:", valorfinal)

Fimalgoritmo