Algoritmo "Atv7exc4"

Var

modelo:caractere
ano:real
consumo:real
valorfinal:real

Inicio

escreval ("informe o modelo do veiculo")
leia (modelo)
escreval ("informe o ano do veiculo")
leia (ano)
escreval ("informe o consumo por litro do veiculo")
leia (consumo)
valorfinal:= 736/consumo
escreva ("para percorrer 736km o veiculo precisa de:", valorfinal)
escreval (" litros")

Fimalgoritmo